name: esp32_ai
description: A sample command-line application.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.3
  dart_jsonwebtoken: ^3.3.1
  http: ^1.6.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  uuid: ^4.5.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
